### ISSUE TITLE
Ubuntu Touch: sound kernel modules probe automatically

### ISSUE THREAD

**Issue by RossComputerGuy** [Oleffa/pinephone-guides#1]
> ```
> modprobe snd_soc_simple_amplifier
> modprobe snd_soc_simple_card_utils
> ```

Ubuntu Touch has this part of audio fixed. I don't think we need this in the markdown file.

**Comment by Oleffa** [comment]
Hi thanks for letting me know! Tested it on build #222 and these lines are not needed anymore.
